/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,jsx,ts,tsx}",
    "./components/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  presets: [require("nativewind/preset")],
  theme: {
    extend: {
      colors: {
        // ── Tokens semánticos ──────────────────────────────────────────
        background:              '#FAFAFA',
        'background-dark':       '#0D0D0D',
        surface:                 '#FFFFFF',
        'surface-dark':          '#1A1A1A',
        'surface-raised':        '#F5F5F5',
        'surface-raised-dark':   '#222222',
        'surface-overlay':       '#F3F4F6',
        'surface-overlay-dark':  '#2A2A2A',
        border:                  '#ECECEC',
        'border-dark':           '#2A2A2A',
        'border-strong':         '#E0E0E0',
        'border-strong-dark':    '#3A3A3A',
        foreground:              '#000000',
        'foreground-dark':       '#F0F0F0',
        'foreground-muted':      '#6B7280',
        'foreground-muted-dark': '#8A8A8A',
        'foreground-subtle':     '#9CA3AF',
        'foreground-subtle-dark':'#606060',
        'input-bg':              '#F3F4F6',
        'input-bg-dark':         '#1E1E1E',
        'gold-surface':          '#FAF3DF',
        'gold-surface-dark':     '#1A1700',
        destructive:             '#EF4444',
        'destructive-dark':      '#F87171',
        // ── Primitivos existentes (sin cambio) ─────────────────────────
        gold: {
          DEFAULT: '#D4AF37',
          light: '#F4E0A0',
          dark: '#A48A27',
          border: '#E4D39C',
          'border-alt': '#E8D49E',
          bg: '#FAF3DF',
          'bg-soft': '#F9F7F0',
          text: '#8D6C1A',
          decor: '#E8DCC0',
          check: '#C4A35A',
        },
        premium: {
          black: '#000000',
          'black-soft': '#121212',
          white: '#FFFFFF',
          'white-soft': '#FAFAFA',
          'white-pale': '#F9FAFB',
          'white-dim': '#F7F7F7',
          gray: {
            DEFAULT: '#6B7280',
            light: '#E5E5E5',
            dark: '#404040',
            secondary: '#9CA3AF',
            caption: '#94A3B8',
            'caption-alt': '#B2BAC8',
            medium: '#8E8E8E',
            soft: '#A7A7A7',
            faint: '#A3A3A3',
            icon: '#737373',
            'icon-muted': '#C7CBD1',
            pale: '#D1D5DB',
            track: '#D4D4D4',
          },
          surface: {
            DEFAULT: '#F5F5F5',
            alt: '#F4F4F4',
            soft: '#F3F4F6',
            section: '#F1F1F1',
            pale: '#FBFBFB',
          },
          divider: {
            DEFAULT: '#ECECEC',
            subtle: '#F0F0F0',
            soft: '#E9E9E9',
            faint: '#EAEAEA',
            lighter: '#EFEFEF',
            medium: '#E0E0E0',
            strong: '#E5E7EB',
            muted: '#DDDDDD',
            'fav-btn': '#E6E6E6',
            disabled: '#D0D0D0',
            switch: '#D9DDE2',
          },
        },
        error: {
          DEFAULT: '#EF4444',
          dark: '#DC2626',
          bg: '#FDECEC',
          campaign: '#F44336',
        },
        success: {
          DEFAULT: '#10B981',
          text: '#16A34A',
          campaign: '#4CAF50',
        },
        warning: {
          DEFAULT: '#F59E0B',
          text: '#D97706',
        },
      },
      fontFamily: {
        manrope: ['Manrope_400Regular'],
        'manrope-medium': ['Manrope_500Medium'],
        'manrope-semibold': ['Manrope_600SemiBold'],
        'manrope-bold': ['Manrope_700Bold'],
        'manrope-extrabold': ['Manrope_800ExtraBold'],
      },
      boxShadow: {
        'premium-gold': '0 10px 25px -5px rgba(212, 175, 55, 0.4)',
        'premium-black': '0 20px 40px -12px rgba(0, 0, 0, 0.3)',
        'premium-soft': '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
      },
      borderRadius: {
        'premium-sm': '12px',
        'premium-md': '20px',
        'premium-lg': '28px',
        'premium-xl': '36px',
      }
    },
  },
  plugins: [],
}
