// Catálogo centralizado de iconos de la app.
// Si se cambia la librería de iconos, SOLO se toca este fichero.
import {
  Scissors,
  Calendar,
  Star,
  MapPin,
  MessageCircle,
  ChevronRight,
  Plus,
  X,
  Check,
  CheckCircle2,
  User,
  Clock,
  Search,
  Home,
  AlertCircle,
  Loader,
  Mail,
  Phone,
  Settings,
  Navigation,
  ChevronDown,
  ArrowUpRight,
  Tag,
  ArrowLeft,
  Sparkles,
  Send,
  Trash2,
  Heart,
  Leaf,
  Recycle,
  Wind,
} from 'lucide-react-native'

export {
  Scissors      as IconScissors,
  Calendar      as IconCalendar,
  Star          as IconStar,
  MapPin        as IconLocation,
  MessageCircle as IconChat,
  ChevronRight  as IconChevron,
  Plus          as IconAdd,
  X             as IconClose,
  Check         as IconCheck,
  CheckCircle2  as IconCheckCircle,
  User          as IconUser,
  Clock         as IconClock,
  Search        as IconSearch,
  Home          as IconHome,
  AlertCircle   as IconError,
  Loader        as IconLoader,
  Mail          as IconMail,
  Phone         as IconPhone,
  Settings      as IconSettings,
  Navigation    as IconNearMe,
  ChevronDown   as IconExpandMore,
  ArrowUpRight  as IconArrowUpRight,
  Tag           as IconTag,
  ArrowLeft     as IconBack,
  Sparkles      as IconSparkles,
  Send          as IconSend,
  Trash2        as IconTrash,
  Heart         as IconHeart,
  Leaf          as IconLeaf,
  Recycle       as IconRecycle,
  Wind          as IconWind,
}
