// Catálogo centralizado de iconos de la app.
// Si se cambia la librería de iconos, SOLO se toca este fichero.
import {
  Scissors,
  Calendar,
  Star,
  MapPin,
  MessageCircle,
  ChevronRight,
  ChevronLeft,
  Plus,
  X,
  Check,
  CheckCircle2,
  User,
  Clock,
  Search,
  Home,
  AlertCircle,
  Loader,
  Mail,
  Phone,
  Settings,
  Navigation,
  ChevronDown,
  ArrowUpRight,
  Tag,
} from 'lucide-react-native'

export {
  Scissors      as IconScissors,
  Calendar      as IconCalendar,
  Star          as IconStar,
  MapPin        as IconLocation,
  MessageCircle as IconChat,
  ChevronRight  as IconChevron,
  ChevronLeft   as IconBack,
  Plus          as IconAdd,
  X             as IconClose,
  Check         as IconCheck,
  CheckCircle2  as IconCheckCircle,
  User          as IconUser,
  Clock         as IconClock,
  Search        as IconSearch,
  Home          as IconHome,
  AlertCircle   as IconError,
  Loader        as IconLoader,
  Mail          as IconMail,
  Phone         as IconPhone,
  Settings      as IconSettings,
  Navigation    as IconNearMe,
  ChevronDown   as IconExpandMore,
  ArrowUpRight  as IconNorthWest,
  Tag           as IconTag,
}
